/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}


//crm-console/
//        ├─ src/main/java/
//        │  └─ com/company/crm/
//        │     ├─ config/
//        │     │   └─ AppConfig.java
//        │     ├─ model/
//        │     │   ├─ Employee.java
//        │     │   ├─ Client.java
//        │     │   ├─ RealObject.java
//        │     │   └─ Task.java
//        │     ├─ dao/
//        │     │   ├─ interfaces/
//        │     │   │   ├─ EmployeeDao.java
//        │     │   │   ├─ ClientDao.java
//        │     │   │   ├─ RealObjectDao.java
//        │     │   │   └─ TaskDao.java
//        │     │   └─ inmemory/
//        │     │       ├─ EmployeeDaoInMemory.java
//        │     │       ├─ ClientDaoInMemory.java
//        │     │       ├─ RealObjectDaoInMemory.java
//        │     │       └─ TaskDaoInMemory.java
//        │     ├─ service/
//        │     │   ├─ interfaces/
//        │     │   │   ├─ EmployeeService.java
//        │     │   │   ├─ ClientService.java
//        │     │   │   └─ ...
//        │     │   └─ impl/
//        │     │       ├─ EmployeeServiceImpl.java
//        │     │       └─ ...
//        │     ├─ controller/
//        │     │   ├─ ConsoleApp.java
//        │     │   ├─ EmployeeController.java
//        │     │   ├─ ClientController.java
//        │     │   └─ ...
//        │     ├─ util/
//        │     │   ├─ ConsoleHelper.java
//        │     │   └─ Validators.java
//        │     └─ Main.java
//        ├─ pom.xml (или build.gradle)
//        └─ README.md
