/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.11/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
    war
    id("org.gretty") version "4.1.0"
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // This dependency is used by the application.
    implementation(libs.guava)
    implementation(libs.postgresql)
    implementation(libs.junit.jupiter)
    implementation(libs.servlet)
    implementation(libs.servlet.jsp)
    implementation(libs.servlet.jstl.api)
    implementation(libs.servlet.jstl)
    implementation(libs.tomcat.embed.core)
    implementation(libs.tomcat.embed.jasper)

    implementation(libs.jdt)
